if: 'tag IS blank'
env:
    global:
        - TRAVIS_TAG=v2021.8.25
jobs:
    include:
        # -
            # name: 'Python 3.8.10 on Linux (AMD64)'
            # os: linux
            # dist: focal   # python3.8.10 include in osx:focal
            # arch: amd64
            # language: shell
            # # language: python
            # # python: 3.8.10 # 别用, travis自带的包库太多，还不能用python3 -m venv进虚拟环境，编译出来应用程序体积太大
            # env: ['PATH=~/.ruby/bin:$PATH', GEM_HOME=~/.ruby, RELEASE_FILENAME=CDNDrivePro-$TRAVIS_TAG-linux-amd64.tar.gz]
            # before_install: 
                # - 'sudo apt-get update && sudo apt install -y python3.8-venv'
                # - 'python3 -m venv tmpbuild && source tmpbuild/bin/activate'
        # -
            # name: 'Python 3.8.10 on Linux (ARM64)'
            # os: linux
            # dist: focal
            # arch: arm64
            # language: shell
            # env: ['PATH=~/.ruby/bin:$PATH', GEM_HOME=~/.ruby, RELEASE_FILENAME=CDNDrivePro-$TRAVIS_TAG-linux-arm64.tar.gz]
            # before_install: 
                # - 'sudo apt-get update && sudo apt install -y python3.8-venv'
                # - 'python3 -m venv tmpbuild && source tmpbuild/bin/activate'
        # -
            # name: 'Python 3.8.6 on macOS (AMD64)'
            # os: osx
            # osx_image: xcode11.6  # python3.8.6 include in osx:xcode11.6
            # arch: amd64
            # language: shell
            # env: RELEASE_FILENAME=CDNDrivePro-$TRAVIS_TAG-macos-amd64.zip
            # before_install: 'python3 -m venv tmpbuild && source tmpbuild/bin/activate'
        # -
            # name: 'Python 3.8.10 win64 on Windows (AMD64)'
            # os: windows
            # arch: amd64
            # language: shell
            # env: ['PATH=/c/Python38:/c/Python38/Scripts:$PATH', RELEASE_FILENAME=CDNDrivePro-$TRAVIS_TAG-win64-amd64.zip]
            # before_install: 
                # - 'choco install python --version=3.8.10'
                # - 'python -m venv tmpbuild && tmpbuild/Scripts/activate.bat'
        -
            name: 'Python 3.8.10 win32 on Windows (AMD64)'
            os: windows
            arch: amd64
            language: shell
            env: ['PATH=/c/Python38:/c/Python38/Scripts:$PATH', RELEASE_FILENAME=CDNDrivePro-$TRAVIS_TAG-win32-amd64.zip]
            before_install: 
                - '7z x ./win32bit/python-3.8.10-32bit.7z -o/c/'
                - '/c/Python38/tmpbuild/Scripts/activate.bat'
install:
    - 'if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m pip install -U pip; else pip3 install -U pip; fi'
    - 'pip3 install -r requirements.txt'
    - 'pip3 install pyinstaller'
script:
    - 'if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m CDNDrivePro -v; else python3 -m CDNDrivePro -v; fi'
    - 'pyinstaller -F -n CDNDrivePro -i icon.ico CDNDrivePro/__main__.py'
    - 'mkdir -p release/CDNDrivePro'
    - 'cp {dist/*,LICENSE,README.md} release/CDNDrivePro'
    - 'cd release'
    - 'if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z a -tzip $RELEASE_FILENAME CDNDrivePro; elif [ "$TRAVIS_OS_NAME" = "osx" ]; then zip -r $RELEASE_FILENAME CDNDrivePro; else tar -czvf $RELEASE_FILENAME CDNDrivePro; fi'
    - 'cd ..'
deploy:
    -
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: release/$RELEASE_FILENAME
        overwrite: true
        skip_cleanup: true
    -
        provider: pypi
        user: __token__
        password: $PYPI_API_TOKEN
        distributions: 'pip3 install twine && sdist bdist_wheel'  # twine为上传pypi的工具最后安装，减少pyinstaller编译的应用程序体积
        skip_existing: true
        on:
            condition: ['$TRAVIS_OS_NAME = linux', '$TRAVIS_CPU_ARCH = amd64']
