# pypi的打包独立出来，让pyinstaller打包尽可能小（不安装twine）
if: 'tag IS blank'
env:
    global:
        - TRAVIS_TAG=v2021.8.25.1
jobs:
    include:
        -
            name: 'Python 3.6.8 on Linux (AMD64)'
            os: linux
            dist: xenial
            arch: amd64
            language: python
            python: 3.6.8 # 使用最低要求版本，增强兼容性
            env: ['PATH=~/.ruby/bin:$PATH', GEM_HOME=~/.ruby]
deploy:
    provider: pypi
    user: __token__
    password: $PYPI_API_TOKEN
    distributions: 'sdist bdist_wheel'
    skip_existing: true
    on:
        condition: ['$TRAVIS_OS_NAME = linux', '$TRAVIS_CPU_ARCH = amd64']
